---
title: "Attrition Model Selection"
author: "George M. Ndede"
date: "12/01/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(relaimpo)
library(MASS)
```

```{r regression_common}
numeric_predictors <- c("Age",
"t_DistanceFromHome",
"t_Education",
"t_EnvironmentSatisfaction",
"t_JobInvolvement",
"t_JobLevel",
"t_JobSatisfaction",
"t_NumCompaniesWorked",
"t_PercentSalaryHike",
"t_PerformanceRating",
"t_RelationshipSatisfaction",
"t_StockOptionLevel",
"t_TotalWorkingYears",
"t_TrainingTimesLastYear",
"t_WorkLifeBalance",
"t_YearsAtCompany",
"t_YearsInCurrentRole",
"t_YearsSinceLastPromotion",
"t_YearsWithCurrManager",
"numeric_OverTime",
"numeric_MaritalStatus")

factor_predictors <- c("BusinessTravel",
"Department",
"EducationField",
"Gender",
"JobRole",
"MaritalStatus")

all_predictors <- c(numeric_predictors,factor_predictors)

att_f_all <- as.formula(paste("numeric_attrition ~ ",
                             paste(all_predictors,collapse="+")))

att_f_num <- as.formula(paste("numeric_attrition ~ ",
                              paste(numeric_predictors,collapse="+")))

att_f_fac <- as.formula(paste("numeric_attrition ~ ",
                              paste(factor_predictors,collapse="+")))
```

```{r select_nb_predictors}
fit_nb <- lm(att_f_all, data=employee_data)
fit_nb$call
anova(fit_nb)

stepwise_nb <- stepAIC(fit_nb,direction="both",trace=0)
stepwise_nb$call
anova(stepwise_nb)
```

```{r select_knn_predictors}
fit_knn <- lm(att_f_num, data=employee_data)
fit_knn$call
anova(fit_knn)

stepwise_knn <- stepAIC(fit_knn,direction="both",trace=0)
stepwise_knn$call
anova(stepwise_knn)
```